### ISSUE TITLE
[Feature] 함께 성장해요 메인 페이지 컴포넌트 생성

### ISSUE THREAD

**Issue by dotory0829** [FC-Palette/Palette-FE#14]
### Description

- common
    
    `SubHeader.tsx`: 공용 서브헤더 컴포넌트 `작성완료`
    
- constants
    - career
        - `careerFilter.ts`: 메인 서브헤더 텍스트 `작성완료`
        - `careerWriteBtnText.ts`: 메인 글쓰기(모임생성) 텍스트 `작성완료`
        - `index.ts`: named export용
- career
    - main(메인)
        - `index.ts`: named export용 `작성완료`
        - `careerMainCard`: 커리어 메인 페이지 게시글 `**전체**` `Wrapper` 컴포넌트 `작성완료`
            - `CareerMainItemsWrap`: 커리어 모임 리스트 내 **`아이템(모임글정보)`** `Wrapper` 컴포넌트 `작성완료`
                - `CareerMainItemTitle.tsx` = 커리어 모임 리스트 내 **`아이템`** `타이틀` 컴포넌트 `작성완료`
                - `CareerMainItemTime.tsx` = 커리어 모임 리스트 내 **`아이템`** `모임시간` 컴포넌트 `작성완료`
                - `CareerMainItemCategory.tsx` = 커리어 모임 리스트 내 **`아이템`** `카테고리` 컴포넌트 `작성완료`
                - `CareerMainItemImage.tsx` = 커리어 모임 리스트 내 **`아이템`** `대표이미지` 컴포넌트 `작성완료`
                - `CareerMainItemParticipant.tsx` = 커리어 모임 리스트 내 `**아이템**` `참가자` 컴포넌트 `작성완료`
                - `CareerMainItemLikeButton.tsx` = 커리어 모임 리스트 `**아이템**` `하트버튼` 컴포넌트 `작성완료`
                - `CareerMainItemCreateButton.tsx` = 커리어 모임 리스트 `**아이템**` `글쓰기` 컴포넌트 `작성완료`
                - `CareerMainFilterBar.tsx` = 커리어 모임 메인 `필터` 컴포넌트 `작성완료`
                - `CareerMainFilterSortOption.tsx` = 커리어 모임 메인 `필터옵션` 컴포넌트 [최신순, 오래된순] `작성완료`

**Comment by hookor** [comment]
좋습니다 우측에 딱지 붙여주시면 더 좋을 것 같고 체크리스트로 만드시면 작업하실 때 더 편하실 거 같은디 이 부분은 개인 선호니까 고려해보셔도 좋을 것 같아 말씀드립니다! 수고하셨어용
