### ISSUE TITLE
[Feature] 시작 , 로그인 페이지 ui 구현 완료

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#17]
### Description

시작(/start) 페이지 ui 적용 완료. (정확한 ui 위치는 추후 조정필요)
로그인(/signin) 페이지 ui 적용 완료. (정확한 ui 위치 추후 조정 필요, 정규식 에러 메세지에 아이콘 추가 필요)

회원가입(/signup), 아이디 찾기(/findid), 비밀번호 찾기(/findpassword)  페이지는 라우팅만 완료.
작업 순서 후순위

**Comment by hookor** [comment]
좋습니다 담에 작성하실 땐 첨에 말했듯이 마크다운 활용해서(bulleted list,numbered list) 보기좋게만 해주시면 완벽해요🔥

**Comment by hookor** [comment]
우측에 assignees랑projects도 붙이는 거 잊지 말아주세요
