### ISSUE TITLE
[Feature]알림 페이지 1차 Ui 적용 완료

### ISSUE THREAD

**Issue by dragon-it** [FC-Palette/Palette-FE#48]
### Description

<img width="324" alt="image" src="https://github.com/FC-Palette/Palette-FE/assets/118169266/b9ee598b-1f1f-4d77-a33b-7f266f132a58">

- 선택한 탭에 따라 카테고리 다르게 렌더링 됨.
- 모두읽음, 상세페이지 구현 필요

**Comment by hookor** [comment]
좋 와 용
